### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Misha279-UA** [Wehrmachtserdbeere/MDRG-Analyzer#3]
![image](https://github.com/Wehrmachtserdbeere/MDRG-Analyzer/assets/156463244/8f5533a1-cc4d-47f9-b7c2-32c31383d80f)
i try to give me more money
this is VERY new safe (new game, save game)

**Comment by Misha279-UA** [comment]
i just klicked random buttons on my antivirus and now it work

**Comment by Wehrmachtserdbeere** [comment]
Yea, it seems to have messed up because of restricted permissions. I recommend first trying to run it as an administrator before messing with your antivirus, unless the antivirus is what restricts it.
