### ISSUE TITLE
master

### ISSUE THREAD

**Issue by Misha279-UA** [Wehrmachtserdbeere/MDRG-Analyzer#5]
master version don't have app, and i dont know how to find not master

**Comment by Wehrmachtserdbeere** [comment]
I have no idea what you are trying to ask.

**Comment by Wehrmachtserdbeere** [comment]
Also please add labels if you can. It makes it easier to sort issues.

**Comment by Misha279-UA** [comment]
i mean in code page we have MDRG analiser master what is just folder with random files, but without any exe.
i new in GitHub so i dont know if I do somesing wrong

> Also please add labels if you can. It makes it easier to sort issues
> i wery new in GitHub so i dont know if I do somesing wrong

**Comment by Wehrmachtserdbeere** [comment]
On the normal site, you look at the right and click on "Releases". There you will find the zip file with the program in it.
