### ISSUE TITLE
it's me again

### ISSUE THREAD

**Issue by Misha279-UA** [Wehrmachtserdbeere/MDRG-Analyzer#6]
![image](https://github.com/Wehrmachtserdbeere/MDRG-Analyzer/assets/156463244/3ef8167a-aaa3-4265-b955-a3da7d7bf8ad)
it's day 3 i trying use this app, and it still not work, if there any troubleshooting guide? becouse it was realy good thing in 0.86

**Comment by Wehrmachtserdbeere** [comment]
Like I said before, this is a bug in the current version. It incorrectly states that it is version "1.1.0" due to an oversight. The current release is the version "1.1.1". This oversight will be fixed in "1.1.2".

**Comment by Misha279-UA** [comment]
oh, thanks, i think it alredy fixed and it i stupid, and can't download, but it just not fixed yet.
